#!/bin/bash

echo "Exporting variables..."

export IMAGE=$(sed -n '1p' /tmp/.auth)
export BUILD_TAG=$(sed -n '2p' /tmp/.auth)
export PASS=$(sed -n '3p' /tmp/.auth)

echo " Logging in docker hub..."

docker login -u kom07 -p $PASS

echo "Starting service maven from docker compose..."

cd maven && docker-compose up -d

